version: '3.8'

services:
  bot:
    image: ghcr.io/danielhkuo/walpurgisbot-v2:latest
    container_name: walpurgisbot-v2
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /mnt/user/appdata/walpurgisbot-v2:/app/data