services:
  bot:
    image: ghcr.io/danielhkuo/walpurgisbot-v2:latest
    container_name: walpurgisbot-v2
    restart: unless-stopped

    environment:
      - NODE_ENV=production
      - MIGRATIONS_PATH=/app/src/database/migrations
      - MIGRATIONS_PATH=/migrations
      - DATABASE_PATH=/app/data/walpurgis.db

    env_file:
      - .env

    volumes:
      - walpurgisbot_data:/app/data