# .github/workflows/publish-docker-image.yml
name: Publish to GHCR

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # This is the main event: it builds your Dockerfile and pushes it.
      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/walpurgisbot-v2:latest
            ghcr.io/${{ github.repository_owner }}/walpurgisbot-v2:${{ github.sha }}
          # --- FIX: Add this build-args block ---
          build-args: |
            NODE_ENV=production